export const FR2_CORPUS: Array<{ message: string; slug: string }> = [
  { message: 'wifi', slug: 'wifi-qr-code' },
  { message: 'wi-fi', slug: 'wifi-qr-code' },
  { message: 'wi fi', slug: 'wifi-qr-code' },
  { message: 'uifi', slug: 'wifi-qr-code' },
  { message: 'wify', slug: 'wifi-qr-code' },
  { message: 'wiffi', slug: 'wifi-qr-code' },
  { message: 'senha do wifi', slug: 'wifi-qr-code' },
  { message: 'qr do wifi', slug: 'wifi-qr-code' },
  { message: 'rede wifi', slug: 'wifi-qr-code' },
  { message: 'gov.br', slug: 'codigo-govbr' },
  { message: 'govbr', slug: 'codigo-govbr' },
  { message: 'gov br', slug: 'codigo-govbr' },
  { message: 'goovi', slug: 'codigo-govbr' },
  { message: 'governo', slug: 'codigo-govbr' },
  { message: 'codigo do gov', slug: 'codigo-govbr' },
  { message: 'gov brasi', slug: 'codigo-govbr' },
  { message: 'whatsapp', slug: 'whatsapp-contato-localizacao' },
  { message: 'whatsap', slug: 'whatsapp-contato-localizacao' },
  { message: 'watsap', slug: 'whatsapp-contato-localizacao' },
  { message: 'uatsap', slug: 'whatsapp-contato-localizacao' },
  { message: 'zap', slug: 'whatsapp-contato-localizacao' },
  { message: 'whats', slug: 'whatsapp-contato-localizacao' },
  { message: 'watzap', slug: 'whatsapp-contato-localizacao' },
  { message: 'pix', slug: 'fazer-pix' },
  { message: 'pics', slug: 'fazer-pix' },
  { message: 'pixx', slug: 'fazer-pix' },
  { message: 'fazer um pix', slug: 'fazer-pix' },
  { message: 'pikis', slug: 'fazer-pix' },
  { message: 'boleto', slug: 'segunda-via-boleto' },
  { message: 'boletu', slug: 'segunda-via-boleto' },
  { message: 'boletoo', slug: 'segunda-via-boleto' },
  { message: 'segunda via', slug: 'segunda-via-boleto' },
  { message: '2 via', slug: 'segunda-via-boleto' },
  { message: 'conta atrasada', slug: 'segunda-via-boleto' },
  { message: 'golpe', slug: 'alerta-golpe' },
  { message: 'golpi', slug: 'alerta-golpe' },
  { message: 'fraude', slug: 'alerta-golpe' },
  { message: 'mensagem estranha', slug: 'alerta-golpe' },
  { message: 'link suspeito', slug: 'alerta-golpe' },
];

export const NEGATIVE_PAIRS: Array<{ message: string; slug: string; forbidden: string }> = [
  { message: 'senha do wifi', slug: 'wifi-qr-code', forbidden: 'codigo-govbr' },
  { message: 'fazer um pix', slug: 'fazer-pix', forbidden: 'segunda-via-boleto' },
  { message: 'segunda via', slug: 'segunda-via-boleto', forbidden: 'fazer-pix' },
  { message: 'watsap', slug: 'whatsapp-contato-localizacao', forbidden: 'alerta-golpe' },
  { message: 'mensagem estranha', slug: 'alerta-golpe', forbidden: 'whatsapp-contato-localizacao' },
];

export const TOPIC_CATALOG = [
  { slug: 'wifi-qr-code', title: 'Senha do Wi-Fi via QR Code' },
  { slug: 'codigo-govbr', title: 'Código Gov.br (tutorial)' },
  { slug: 'fazer-pix', title: 'Como fazer um PIX' },
  { slug: 'segunda-via-boleto', title: '2ª via de boleto' },
  { slug: 'whatsapp-contato-localizacao', title: 'WhatsApp: contato e localização' },
  { slug: 'alerta-golpe', title: 'Reconhecer possível golpe' },
];
