// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC85vol-4zUTqtUti0yrykidZ0CGvg7Oq4',
    appId: '1:678556404846:web:1f3f55a7ab3a9443576a7f',
    messagingSenderId: '678556404846',
    projectId: 'conecta-geracao',
    authDomain: 'conecta-geracao.firebaseapp.com',
    storageBucket: 'conecta-geracao.firebasestorage.app',
    measurementId: 'G-S17PM942N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ15JRWDa-RSt5J_gD_yX86KPebEuVVdw',
    appId: '1:678556404846:android:c35def4b079e8eb0576a7f',
    messagingSenderId: '678556404846',
    projectId: 'conecta-geracao',
    storageBucket: 'conecta-geracao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB19UyoEQBinjcQ3XIBfRegT0POemRtFwk',
    appId: '1:678556404846:ios:240e3e385439ddf9576a7f',
    messagingSenderId: '678556404846',
    projectId: 'conecta-geracao',
    storageBucket: 'conecta-geracao.firebasestorage.app',
    iosBundleId: 'com.conectageracao.conectaGeracao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB19UyoEQBinjcQ3XIBfRegT0POemRtFwk',
    appId: '1:678556404846:ios:240e3e385439ddf9576a7f',
    messagingSenderId: '678556404846',
    projectId: 'conecta-geracao',
    storageBucket: 'conecta-geracao.firebasestorage.app',
    iosBundleId: 'com.conectageracao.conectaGeracao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC85vol-4zUTqtUti0yrykidZ0CGvg7Oq4',
    appId: '1:678556404846:web:80ee4564933c7f4a576a7f',
    messagingSenderId: '678556404846',
    projectId: 'conecta-geracao',
    authDomain: 'conecta-geracao.firebaseapp.com',
    storageBucket: 'conecta-geracao.firebasestorage.app',
    measurementId: 'G-X5DJDKVJWM',
  );
}
