-- Tabelas do consumo simulado da IA no Oracle local.
-- Sem URL, usuário ou senha. Aplicar já conectado no schema do ambiente.
-- Banco: Oracle 12c ou mais recente, character set AL32UTF8. Arquivo UTF-8.
-- Idempotente: reexecutar não recria objeto que já existe.
-- Não altera o Postgres.

SET DEFINE OFF
WHENEVER SQLERROR EXIT FAILURE

DECLARE
  PROCEDURE garantir_tabela(p_nome IN VARCHAR2, p_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = p_nome;

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_ddl;
    END IF;
  END;

  PROCEDURE garantir_constraint(p_nome IN VARCHAR2, p_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_constraints
     WHERE constraint_name = p_nome;

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_ddl;
    END IF;
  END;

  PROCEDURE garantir_indice(p_nome IN VARCHAR2, p_ddl IN VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_indexes
     WHERE index_name = p_nome;

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE p_ddl;
    END IF;
  END;
BEGIN
  garantir_tabela(
    'USUARIO_CONSUMO',
    'CREATE TABLE USUARIO_CONSUMO (
       ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
       NOME VARCHAR2(120 CHAR) NOT NULL,
       IDENTIFICADOR_EXTERNO VARCHAR2(64 CHAR) NOT NULL
     )'
  );

  garantir_tabela(
    'LEITURA_CONSUMO',
    'CREATE TABLE LEITURA_CONSUMO (
       ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
       USUARIO_ID NUMBER NOT NULL,
       QUANTIDADE_TOKENS NUMBER(12) NOT NULL,
       INSTANTE TIMESTAMP NOT NULL
     )'
  );

  garantir_tabela(
    'ALERTA_CONSUMO',
    'CREATE TABLE ALERTA_CONSUMO (
       ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
       USUARIO_ID NUMBER NOT NULL,
       INICIO TIMESTAMP NOT NULL,
       FIM TIMESTAMP NOT NULL,
       TOTAL_TOKENS NUMBER(12) NOT NULL,
       MENSAGEM VARCHAR2(400 CHAR) NOT NULL,
       CRIADO_EM TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
     )'
  );

  garantir_constraint(
    'PK_USUARIO_CONSUMO',
    'ALTER TABLE USUARIO_CONSUMO ADD CONSTRAINT PK_USUARIO_CONSUMO PRIMARY KEY (ID)'
  );
  garantir_constraint(
    'UK_USUARIO_CONSUMO_EXT',
    'ALTER TABLE USUARIO_CONSUMO ADD CONSTRAINT UK_USUARIO_CONSUMO_EXT UNIQUE (IDENTIFICADOR_EXTERNO)'
  );

  garantir_constraint(
    'PK_LEITURA_CONSUMO',
    'ALTER TABLE LEITURA_CONSUMO ADD CONSTRAINT PK_LEITURA_CONSUMO PRIMARY KEY (ID)'
  );
  -- Sem ON DELETE CASCADE: a leitura não some junto com o usuário.
  garantir_constraint(
    'FK_LEITURA_USUARIO',
    'ALTER TABLE LEITURA_CONSUMO ADD CONSTRAINT FK_LEITURA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_CONSUMO (ID)'
  );
  garantir_constraint(
    'CK_LEITURA_TOKENS',
    'ALTER TABLE LEITURA_CONSUMO ADD CONSTRAINT CK_LEITURA_TOKENS CHECK (QUANTIDADE_TOKENS >= 0)'
  );
  garantir_indice(
    'IX_LEITURA_USUARIO_INSTANTE',
    'CREATE INDEX IX_LEITURA_USUARIO_INSTANTE ON LEITURA_CONSUMO (USUARIO_ID, INSTANTE)'
  );

  garantir_constraint(
    'PK_ALERTA_CONSUMO',
    'ALTER TABLE ALERTA_CONSUMO ADD CONSTRAINT PK_ALERTA_CONSUMO PRIMARY KEY (ID)'
  );
  -- Sem ON DELETE CASCADE. A UK reserva um alerta por usuário e período.
  garantir_constraint(
    'FK_ALERTA_USUARIO',
    'ALTER TABLE ALERTA_CONSUMO ADD CONSTRAINT FK_ALERTA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_CONSUMO (ID)'
  );
  garantir_constraint(
    'CK_ALERTA_TOKENS',
    'ALTER TABLE ALERTA_CONSUMO ADD CONSTRAINT CK_ALERTA_TOKENS CHECK (TOTAL_TOKENS >= 0)'
  );
  garantir_constraint(
    'CK_ALERTA_PERIODO',
    'ALTER TABLE ALERTA_CONSUMO ADD CONSTRAINT CK_ALERTA_PERIODO CHECK (INICIO <= FIM)'
  );
  garantir_constraint(
    'UK_ALERTA_USUARIO_PERIODO',
    'ALTER TABLE ALERTA_CONSUMO ADD CONSTRAINT UK_ALERTA_USUARIO_PERIODO UNIQUE (USUARIO_ID, INICIO, FIM)'
  );

  EXECUTE IMMEDIATE q'[
    COMMENT ON TABLE USUARIO_CONSUMO IS
      'Pessoa simulada do Conecta Geração. O identificador externo é fictício.'
  ]';
  EXECUTE IMMEDIATE q'[
    COMMENT ON TABLE LEITURA_CONSUMO IS
      'Ponto da série simulada de tokens. Várias leituras por usuário ao longo do tempo.'
  ]';
  EXECUTE IMMEDIATE q'[
    COMMENT ON TABLE ALERTA_CONSUMO IS
      'Alerta de consumo alto. PR_REGISTRAR_ALERTA_CONSUMO insere no máximo uma linha por usuário e período.'
  ]';
END;
/
